### ISSUE TITLE
karma/ not in .bin/

### ISSUE THREAD

**Issue by johnnymo87** [ssaunier/angular-rails-example#1]
Hi there, I'm following your [blog post](http://sebastien.saunier.me/blog/2014/02/04/angular--rails-with-no-fuss.html) to get setup with karma with rails. I noticed that the [rake task](https://github.com/ssaunier/angular-rails-example/blob/master/lib/tasks/karma.rake) is trying to run `system "./node_modules/.bin/karma #{command} #{f.path} #{args}"`, which is odd because I have no such directory in `.bin/`. It looks like everything I might need is in  `./node_modules/karma/`, should I manually be moving everything from there in `./node_modules/.bin/`? Or is there a better way?

**Comment by ssaunier** [comment]
Hi @johnnymo87 ,

I ran again npm install on a clean clone and I didn't have either my karma executable in `node_modules/.bin`. Weird. I update the code to look it elsewhere, see https://github.com/ssaunier/angular-rails-example/commit/c64b4a6e495def00faee81eba668b44515880c84

Thanks for the bug report!
